workspace:
  - ./*

client:
  - packages/public/client/*
  - packages/public/client/**/*

cloudflare-workers:
  - packages/public/cloudflare-workers/*
  - packages/public/cloudflare-workers/**/*

editor-renderer:
  - packages/public/editor-renderer/*
  - packages/public/editor-renderer/**/*

frontend:
  - packages/public/frontend/*
  - packages/public/frontend/**/*

legacy-editor-renderer:
  - packages/public/legacy-editor-renderer/*
  - packages/public/legacy-editor-renderer/**/*

notifications-job:
  - packages/public/notifications-job/*
  - packages/public/notifications-job/**/*

server:
  - packages/public/server/*
  - packages/public/server/**/*

static-assets:
  - packages/public/static-assets/*
  - packages/public/static-assets/**/*

private:
  - packages/private/**/*

ci:
  - .circleci/*
  - .github/*
  - .github/**/*
